pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/nehap05/WelcomeCOMP367.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying to Tomcat...'
            }
        }
    }
}