pipeline {
  agent any
  tools {
    maven 'MAVEN3'  
  }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        dir('COMP367App') {  
          bat 'mvn clean install' 
        }
      }
    }
  }
}
