pipeline {
    agent any

    tools {
        maven 'MAVEN3'
    }

    environment {
        DOCKER_CREDENTIALS_ID = 'docker-hub'  
        IMAGE_NAME = 'nehap05/maven-webapp'  
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    git branch: 'greeting-feature', 
                        credentialsId: 'your-jenkins-git-credentials-id', 
                        url: 'https://github.com/nehap05/WelcomeCOMP367.git'
                }
            }
        }

        stage('Verify Files') {
            steps {
                dir('COMP367App') {
                    bat 'dir /s /b'  // Verify that Dockerfile exists
                }
            }
        }

        stage('Build Maven Project') {
            steps {
                dir('COMP367App') {  
                    bat 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('COMP367App') {  // Ensures we run inside the right directory
                    bat "docker build -t $IMAGE_NAME ."
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS_ID, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        bat "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    bat "docker push $IMAGE_NAME"
                }
            }
        }

        stage('Deploy Container') {
            steps {
                script {
                    bat """
                        docker stop maven-webapp || echo 'No container running'
                        docker rm maven-webapp || echo 'No container to remove'
                        docker run -d -p 8081:8080 --name maven-webapp $IMAGE_NAME
                    """
                }
            }
        }
    }
}
